flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/default, classpath:db/dev

spring:
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  messages:
    basename: i18n/messages